name: Version Verification

on:
  push:
    branches:
      - '**'

jobs:
  verify-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print current path
        id: path
        run: echo "Current file path $GITHUB_WORKSPACE"
          
      - name: Read Tags from publish.yml
        id: read_tags
        run: |
          tags=$(awk '/tags/{print $2}' .github/workflows/publish.yml)
          tags_without_comma=${tags%,}
          echo "tags::$tags_without_comma" >> $GITHUB_ENV
        
      - name: Use Output
        id: output
        run: echo "Output is ${{ $tags_without_comma }}"
        