name: Version Verification

on:
  push:
    branches:
      - '**'

jobs:
  verify-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Get previous version
        id: previous_version
        run: |
          version=$(git show HEAD^:.github/workflows/publish.yml | awk '/tags/{print $2}' | sed 's/,$//')
          echo "version=$version" >> $GITHUB_ENV
        
      - name: Use Output
        id: output
        run: echo "Output is $version"
        