name: Version Verification

on:
  push:
    branches:
      - '**'

jobs:
  verify-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print current path
        id: path
        run: echo "Current file path $GITHUB_WORKSPACE"

          
      - name: Read Tags from publish.yml
        id: read-tags
        run: echo "{version}=$(awk '/tags/{print $2}' .github/workflows/publish.yml)" >> $GITHUB_OUTPUT "
        
      - name: Use Output
        id: output
        run: echo "Output is ${{ steps.read-tags.outputs.version }}"
        